name: CI/CD
run-name: ${{ github.actor }}/${{ github.event.repository.name }} pipeline
on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build application
        run: yarn add @vue/cli-service && yarn run build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/"
          target: "/var/www/${{ github.repository }}"
